[ADD] removed fields, renamed fields and models cases
Vauxoo/odoo-module-migrator pull request #2
Opened 2024-10-25 11:13 UTC by CLaurelB

2024-10-25 12:39 UTC, CLaurelB commented
@luisg123v could you review, please?

cc. @desdelinux

2025-01-02 15:43 UTC, desdelinux approved these changes

2025-01-28 22:40 UTC, desdelinux approved these changes

2025-01-28 23:19 UTC, luisg123v requested changes

2025-01-28 23:19 UTC, luisg123v commented on odoo_module_migrate/migration_scripts/removed_fields/migrate_130_140/l10n_mx_enterprise.yaml
Shouldn't it be named as the module (`l10n_mx_edi`)? (I'm not so aware of nomenclature.

Same for similar cases.

2025-01-28 23:19 UTC, luisg123v commented on odoo_module_migrate/migration_scripts/renamed_fields/migrate_130_140/product_enterprise.yaml
> +- ['product.template', 'l10n_mx_edi_code_sat_id', 'unspsc_code_id', 'Commit https://github.com/odoo/enterprise/commit/27197e9696aa23cee3396c543aeea45ac5981eca']
I think the correct commit would be: https://github.com/odoo/enterprise/commit/5369fc49a184a4c4e0076e49e729db8de78f0183

2025-01-28 23:31 UTC, CLaurelB commented on odoo_module_migrate/migration_scripts/removed_fields/migrate_130_140/l10n_mx_enterprise.yaml
As far as I can see in the existing files, they combined multiple modules into one file when possible, based on their names. For example, the `account` and `stock` files. That is why I added only `l10n_mx` as the prefix, because there could be modules like `l10n_mx_edi`, `l10n_mx_edi_extended`, `l10n_mx_hr_payroll`, etc., and those could be included in the same file, following the same convention.

2025-01-29 05:39 UTC, CLaurelB commented on odoo_module_migrate/migration_scripts/renamed_fields/migrate_130_140/product_enterprise.yaml
> +- ['product.template', 'l10n_mx_edi_code_sat_id', 'unspsc_code_id', 'Commit https://github.com/odoo/enterprise/commit/27197e9696aa23cee3396c543aeea45ac5981eca']
Updated.

2025-01-30 18:32 UTC, luisg123v commented on odoo_module_migrate/migration_scripts/removed_fields/migrate_130_140/l10n_mx_enterprise.yaml
Then I propose:
`enterprise_l10n_mx`

(repo + sector)

That way, if there are several cases from the same repo, they will be displayed together when listed alphabetically. In the future, we could add more repos like addons-vauxoo, so I think it would be useful to have them easily identifiable.

For cases like `hr-advanced`, all modules will be linked to hr, so there wouldn't be a need to use `hr_advanced_hr`, just `hr_advanced`.

What do you think?

2025-01-30 21:10 UTC, CLaurelB commented on odoo_module_migrate/migration_scripts/removed_fields/migrate_130_140/l10n_mx_enterprise.yaml
I totally agree with this approach. I’ve updated the names accordingly.

2025-01-30 23:59 UTC, luisg123v approved these changes
LGTM :+1:

2025-01-31 00:00 UTC, merged